# Generated by aihubmix-canon (tools/dify/anthropic_routing.py). Do not edit by hand.
"""Payload checks for the thinking-routing prefixes the AiHubMix catalog sync adds to anthropic.py.

The sync appends model prefixes to the routing tuples in `models/llm/anthropic.py` so that
`effort` and adaptive thinking reach the API for models whose yaml exposes them. These cases
pin the resulting request body per model, so a routing regression shows up here instead of as
a silently dropped `effort` or a legacy `budget_tokens` request (which adaptive-only models
reject with 400).
"""

from pathlib import Path
from typing import ClassVar

import pytest
import yaml
from dify_plugin.entities.model.message import UserPromptMessage
from models.llm import anthropic as anthropic_module
from models.llm.anthropic import AnthropicLargeLanguageModel

ADAPTIVE_MODELS = (
    "claude-haiku-5-5",
)
DEFAULT_ON_MODELS = (
    "claude-haiku-5-5",
)
EFFORT_CAP_MODELS = (
    "claude-haiku-5-5",
)

MODEL_DIR = Path(__file__).parents[1] / "models" / "llm"


class _Messages:
    def __init__(self) -> None:
        self.calls: list[dict] = []

    def create(self, **kwargs):
        self.calls.append(kwargs)
        return object()


class _Anthropic:
    instances: ClassVar[list["_Anthropic"]] = []

    def __init__(self, **kwargs) -> None:
        self.messages = _Messages()
        self.instances.append(self)


def _payload(monkeypatch, model: str, model_parameters: dict) -> dict:
    _Anthropic.instances = []
    monkeypatch.setattr(anthropic_module, "Anthropic", _Anthropic)
    AnthropicLargeLanguageModel()._chat_generate(
        model=model,
        credentials={"api_key": "test-key"},
        prompt_messages=[UserPromptMessage(content="Hello")],
        model_parameters=dict(model_parameters),
        stream=True,
    )
    return _Anthropic.instances[0].messages.calls[0]


@pytest.mark.parametrize("model", ADAPTIVE_MODELS)
def test_effort_is_forwarded(monkeypatch, model: str) -> None:
    payload = _payload(monkeypatch, model, {"max_tokens": 16, "effort": "low"})

    assert payload["output_config"]["effort"] == "low"
    assert (payload.get("thinking") or {}).get("type") != "enabled"


@pytest.mark.parametrize("model", ADAPTIVE_MODELS)
def test_enabled_thinking_is_adaptive(monkeypatch, model: str) -> None:
    payload = _payload(monkeypatch, model, {"max_tokens": 16, "thinking": True, "effort": "high"})

    assert payload["thinking"]["type"] == "adaptive"
    assert "budget_tokens" not in payload["thinking"]
    assert payload["output_config"]["effort"] == "high"


@pytest.mark.parametrize("model", DEFAULT_ON_MODELS)
def test_explicit_thinking_off_is_sent_as_disabled(monkeypatch, model: str) -> None:
    payload = _payload(monkeypatch, model, {"max_tokens": 16, "thinking": False, "effort": "low"})

    assert payload["thinking"] == {"type": "disabled"}
    assert payload["output_config"]["effort"] == "low"


@pytest.mark.parametrize("model", DEFAULT_ON_MODELS)
def test_untouched_request_keeps_default_on_thinking(monkeypatch, model: str) -> None:
    # Dify fills every exposed parameter from the yaml default, so the "user changed nothing"
    # request carries the yaml's `thinking` default; for default-on models it must be true.
    schema = yaml.safe_load((MODEL_DIR / f"{model}.yaml").read_text(encoding="utf-8"))
    defaults = {rule["name"]: rule["default"] for rule in schema["parameter_rules"]
                if isinstance(rule, dict) and "default" in rule}
    payload = _payload(monkeypatch, model, defaults)

    assert defaults.get("thinking") is True
    assert payload["thinking"]["type"] == "adaptive"


@pytest.mark.parametrize("model", EFFORT_CAP_MODELS)
@pytest.mark.parametrize("effort", ["xhigh", "max"])
def test_disabled_thinking_clamps_high_effort(monkeypatch, model: str, effort: str) -> None:
    payload = _payload(monkeypatch, model, {"max_tokens": 16, "thinking": False, "effort": effort})

    assert payload["thinking"] == {"type": "disabled"}
    assert payload["output_config"]["effort"] == "high"
