#!/usr/bin/env python3

import argparse
import json
import re
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

DEFAULT_CATALOG_URL = "https://console.tokener.dev/api/public/v1/models"
GENERATED_MARKER = "# Generated by scripts/sync_catalog.py. Do not edit."
MAX_RESPONSE_BYTES = 5 * 1024 * 1024
FALLBACK_MAX_OUTPUT_TOKENS = 65536
DEFAULT_MAX_TOKENS = 8192
ROOT = Path(__file__).resolve().parents[1]
LLM_DIR = ROOT / "models" / "llm"

CAPABILITIES = {
    "streaming",
    "tool_calling",
    "parallel_tool_calling",
    "streaming_tool_calls",
    "vision",
    "structured_output",
    "reasoning",
}
FEATURES = (
    ("tool_calling", "tool-call"),
    ("parallel_tool_calling", "multi-tool-call"),
    ("streaming_tool_calls", "stream-tool-call"),
    ("vision", "vision"),
    ("structured_output", "structured-output"),
)
REVISION_PATTERN = re.compile(r"sha256:[0-9a-f]{64}")


class CatalogError(ValueError):
    pass


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise CatalogError(f"{field} must be a non-empty string")
    return value


def _positive_int(value: Any, field: str) -> int:
    if type(value) is not int or value <= 0:
        raise CatalogError(f"{field} must be a positive integer")
    return value


def _decimal(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise CatalogError(f"{field} must be a decimal string")
    try:
        parsed = Decimal(value)
    except InvalidOperation as ex:
        raise CatalogError(f"{field} must be a decimal string") from ex
    if not parsed.is_finite() or parsed < 0:
        raise CatalogError(f"{field} must be a non-negative decimal string")
    return value


def fetch_catalog(url: str) -> Any:
    request = Request(
        url, headers={"Accept": "application/json", "User-Agent": "tokener-dify-sync"}
    )
    try:
        with urlopen(request, timeout=30) as response:
            body = response.read(MAX_RESPONSE_BYTES + 1)
    except (OSError, URLError) as ex:
        raise CatalogError(f"unable to fetch catalog: {ex}") from ex
    if len(body) > MAX_RESPONSE_BYTES:
        raise CatalogError("catalog response exceeds 5 MiB")
    try:
        return json.loads(body)
    except (UnicodeDecodeError, json.JSONDecodeError) as ex:
        raise CatalogError("catalog response is not valid JSON") from ex


def render_catalog(payload: Any) -> dict[str, str]:
    if not isinstance(payload, dict) or payload.get("schemaVersion") != 1:
        raise CatalogError("catalog schemaVersion must be 1")

    revision = _string(payload.get("catalogRevision"), "catalogRevision")
    if REVISION_PATTERN.fullmatch(revision) is None:
        raise CatalogError("catalogRevision must be a sha256 digest")

    raw_models = payload.get("models")
    if not isinstance(raw_models, list) or not raw_models:
        raise CatalogError("models must be a non-empty array")

    seen: set[str] = set()
    models: list[dict[str, Any]] = []
    for index, raw_model in enumerate(raw_models):
        if not isinstance(raw_model, dict):
            raise CatalogError(f"models[{index}] must be an object")

        model_id = _string(raw_model.get("id"), f"models[{index}].id")
        if model_id in seen:
            raise CatalogError(f"duplicate model id: {model_id}")
        seen.add(model_id)

        model_type = raw_model.get("modelType")
        if model_type == "text-embedding":
            continue
        if model_type != "llm":
            raise CatalogError(f"unsupported model type for {model_id}: {model_type}")

        _string(raw_model.get("label"), f"{model_id}.label")
        _string(raw_model.get("provider"), f"{model_id}.provider")
        if raw_model.get("mode") != "chat":
            raise CatalogError(f"{model_id}.mode must be chat")
        _positive_int(raw_model.get("contextSize"), f"{model_id}.contextSize")

        max_output_tokens = raw_model.get("maxOutputTokens")
        if max_output_tokens is not None:
            _positive_int(max_output_tokens, f"{model_id}.maxOutputTokens")

        capabilities = raw_model.get("capabilities")
        if not isinstance(capabilities, list) or any(
            not isinstance(capability, str) for capability in capabilities
        ):
            raise CatalogError(f"{model_id}.capabilities must be a string array")
        if len(capabilities) != len(set(capabilities)):
            raise CatalogError(f"{model_id}.capabilities contains duplicates")
        unknown = set(capabilities) - CAPABILITIES
        if unknown:
            raise CatalogError(
                f"{model_id}.capabilities contains unknown values: {sorted(unknown)}"
            )
        if "streaming" not in capabilities:
            raise CatalogError(f"{model_id}.capabilities must include streaming")

        pricing = raw_model.get("pricing")
        if not isinstance(pricing, dict):
            raise CatalogError(f"{model_id}.pricing must be an object")
        _string(pricing.get("currency"), f"{model_id}.pricing.currency")
        _decimal(pricing.get("inputPerMillion"), f"{model_id}.pricing.inputPerMillion")
        _decimal(pricing.get("outputPerMillion"), f"{model_id}.pricing.outputPerMillion")
        cache_price = pricing.get("cacheReadPerMillion")
        if cache_price is not None:
            _decimal(cache_price, f"{model_id}.pricing.cacheReadPerMillion")

        if not isinstance(raw_model.get("deprecated"), bool):
            raise CatalogError(f"{model_id}.deprecated must be a boolean")

        models.append(raw_model)

    files: dict[str, str] = {}
    ordered_models = sorted(models, key=lambda model: model["id"])
    for model in ordered_models:
        filename = f"{quote(model['id'], safe='._-')}.yaml"
        files[filename] = _render_model(model, revision)
    files["_position.yaml"] = _render_position(ordered_models, revision)
    return files


def _render_model(model: dict[str, Any], revision: str) -> str:
    capabilities = set(model["capabilities"])
    features = [feature for capability, feature in FEATURES if capability in capabilities]
    pricing = model["pricing"]

    lines = [
        GENERATED_MARKER,
        f"# catalog-revision: {revision}",
        f"model: {json.dumps(model['id'], ensure_ascii=False)}",
        "label:",
        f"  en_US: {json.dumps(model['label'], ensure_ascii=False)}",
        f"  zh_Hans: {json.dumps(model['label'], ensure_ascii=False)}",
        "model_type: llm",
        "features:",
    ]
    lines.extend(f"  - {feature}" for feature in features)
    if not features:
        lines[-1] = "features: []"
    max_output_tokens = model.get("maxOutputTokens")
    if max_output_tokens is None:
        max_output_tokens = min(model["contextSize"], FALLBACK_MAX_OUTPUT_TOKENS)
    lines.extend(
        [
            "model_properties:",
            "  mode: chat",
            f"  context_size: {model['contextSize']}",
            "parameter_rules:",
            "  - name: max_tokens",
            "    use_template: max_tokens",
            f"    default: {min(DEFAULT_MAX_TOKENS, max_output_tokens)}",
            "    min: 1",
            f"    max: {max_output_tokens}",
        ]
    )
    if "structured_output" in capabilities:
        lines.extend(
            [
                "  - name: response_format",
                "    label:",
                "      en_US: Response Format",
                "      zh_Hans: 回复格式",
                "    type: string",
                "    help:",
                "      en_US: Specify the format that the model must output.",
                "      zh_Hans: 指定模型必须输出的格式。",
                "    required: false",
                "    options:",
                "      - text",
                "      - json_object",
                "      - json_schema",
                "  - name: json_schema",
                "    use_template: json_schema",
            ]
        )
    lines.extend(
        [
            "pricing:",
            f"  input: {json.dumps(pricing['inputPerMillion'])}",
            f"  output: {json.dumps(pricing['outputPerMillion'])}",
            '  unit: "0.000001"',
            f"  currency: {json.dumps(pricing['currency'])}",
            f"deprecated: {str(model['deprecated']).lower()}",
        ]
    )
    return "\n".join(lines) + "\n"


def _render_position(models: list[dict[str, Any]], revision: str) -> str:
    lines = [GENERATED_MARKER, f"# catalog-revision: {revision}"]
    lines.extend(f"- {json.dumps(model['id'], ensure_ascii=False)}" for model in models)
    return "\n".join(lines) + "\n"


def sync_files(files: dict[str, str], *, check: bool, output_dir: Path = LLM_DIR) -> bool:
    current = {
        path.name: path.read_text(encoding="utf-8")
        for path in output_dir.glob("*.yaml")
        if path.is_file()
    }
    stale = {
        name
        for name, content in current.items()
        if content.startswith(GENERATED_MARKER) and name not in files
    }
    changed = {name for name, content in files.items() if current.get(name) != content}

    if check:
        if changed or stale:
            for name in sorted(changed | stale):
                print(f"catalog drift: models/llm/{name}", file=sys.stderr)
            return False
        return True

    output_dir.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (output_dir / name).unlink()
    for name in changed:
        (output_dir / name).write_text(files[name], encoding="utf-8")
    print(f"synced {len(files) - 1} LLM models")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Tokener.ai models into Dify YAML")
    parser.add_argument("--url", default=DEFAULT_CATALOG_URL, help="catalog endpoint")
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()

    try:
        files = render_catalog(fetch_catalog(args.url))
        return 0 if sync_files(files, check=args.check) else 1
    except CatalogError as ex:
        print(f"catalog sync failed: {ex}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
