[project]
name = "hubspot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dify-plugin>=0.3.0,<0.5.0",
    "hubspot-api-client~=12.0.0",
    "sentence-transformers~=5.0.0",
]
